# Generated by Django 3.2.4 on 2022-03-07 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scamphotoapp', '0002_auto_20220307_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peoplemodel',
            new_name='PersonModel',
        ),
    ]
