# Generated by Django 3.2.4 on 2022-03-07 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scamphotoapp', '0003_rename_peoplemodel_personmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='age',
            field=models.CharField(choices=[('', '選択してください'), ('10代後半', '10代後半'), ('20代前半', '20代前半'), ('20代後半', '20代後半'), ('30代前半', '30代前半'), ('30代後半', '30代後半'), ('40代前半', '40代前半'), ('40代後半', '40代後半'), ('50代前半', '50代前半'), ('50代後半', '50代後半'), ('60代以上', '60代以上')], default=django.utils.timezone.now, max_length=20, verbose_name='年齢'),
            preserve_default=False,
        ),
    ]
